# Form implementation generated from reading ui file '/home/heracle/code/massmessages/view/firstFortnightWindow.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 700)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.table_fortnight = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.table_fortnight.setObjectName("table_fortnight")
        self.table_fortnight.setColumnCount(6)
        self.table_fortnight.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_fortnight.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_fortnight.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_fortnight.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_fortnight.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_fortnight.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_fortnight.setHorizontalHeaderItem(5, item)
        self.verticalLayout.addWidget(self.table_fortnight)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_selectAll = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_selectAll.setObjectName("btn_selectAll")
        self.horizontalLayout.addWidget(self.btn_selectAll)
        self.btn_deselectAll = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_deselectAll.setObjectName("btn_deselectAll")
        self.horizontalLayout.addWidget(self.btn_deselectAll)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.btn_send = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_send.setObjectName("btn_send")
        self.verticalLayout.addWidget(self.btn_send)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Enviar Mensajes Masivos"))
        item = self.table_fortnight.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Primer Nombre"))
        item = self.table_fortnight.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Segundo Nombre"))
        item = self.table_fortnight.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Primer Apellido"))
        item = self.table_fortnight.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Segundo Apellido"))
        item = self.table_fortnight.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Teléfono"))
        item = self.table_fortnight.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Seleccionar"))
        self.btn_selectAll.setText(_translate("MainWindow", "Seleccionar Todos"))
        self.btn_deselectAll.setText(_translate("MainWindow", "Deseleccionar Todos"))
        self.btn_send.setText(_translate("MainWindow", "Enviar Mensajes"))
