# Form implementation generated from reading ui file '/home/heracle/code/massmessages/view/Login.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_formLogin(object):
    def setupUi(self, formLogin):
        formLogin.setObjectName("formLogin")
        formLogin.resize(546, 433)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/d28c7f7b/banco.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        formLogin.setWindowIcon(icon)
        formLogin.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);\n"
"color: black;")
        self.label = QtWidgets.QLabel(parent=formLogin)
        self.label.setGeometry(QtCore.QRect(200, 20, 131, 111))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/icons/banco.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=formLogin)
        self.label_2.setGeometry(QtCore.QRect(180, 170, 181, 16))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(12)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=formLogin)
        self.label_3.setGeometry(QtCore.QRect(70, 220, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=formLogin)
        self.label_4.setGeometry(QtCore.QRect(70, 270, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.txt_username = QtWidgets.QLineEdit(parent=formLogin)
        self.txt_username.setGeometry(QtCore.QRect(170, 212, 241, 31))
        self.txt_username.setPlaceholderText("")
        self.txt_username.setObjectName("txt_username")
        self.txt_password = QtWidgets.QLineEdit(parent=formLogin)
        self.txt_password.setGeometry(QtCore.QRect(170, 260, 241, 31))
        self.txt_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txt_password.setPlaceholderText("")
        self.txt_password.setObjectName("txt_password")
        self.btn_login = QtWidgets.QPushButton(parent=formLogin)
        self.btn_login.setGeometry(QtCore.QRect(210, 323, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.btn_login.setFont(font)
        self.btn_login.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_login.setStyleSheet("background-color: rgb(255, 190, 111);")
        self.btn_login.setObjectName("btn_login")
        self.lbl_message = QtWidgets.QLabel(parent=formLogin)
        self.lbl_message.setGeometry(QtCore.QRect(30, 400, 491, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_message.setFont(font)
        self.lbl_message.setStyleSheet("color: red;")
        self.lbl_message.setText("")
        self.lbl_message.setObjectName("lbl_message")

        self.retranslateUi(formLogin)
        QtCore.QMetaObject.connectSlotsByName(formLogin)

    def retranslateUi(self, formLogin):
        _translate = QtCore.QCoreApplication.translate
        formLogin.setWindowTitle(_translate("formLogin", "Inicio de sesion"))
        self.label_2.setText(_translate("formLogin", "Inicio de sesion"))
        self.label_3.setText(_translate("formLogin", "Usuario:"))
        self.label_4.setText(_translate("formLogin", "Password:"))
        self.txt_username.setText(_translate("formLogin", "alvaro.quezada"))
        self.txt_password.setText(_translate("formLogin", "Quezada$alvaro23"))
        self.btn_login.setText(_translate("formLogin", "Iniciar"))
