# Form implementation generated from reading ui file '/home/heracle/code/massmessages/view/mainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_main(object):
    def setupUi(self, main):
        main.setObjectName("main")
        main.resize(875, 622)
        self.centralwidget = QtWidgets.QWidget(parent=main)
        self.centralwidget.setObjectName("centralwidget")
        main.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=main)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 875, 20))
        self.menubar.setObjectName("menubar")
        self.menuArchivo = QtWidgets.QMenu(parent=self.menubar)
        self.menuArchivo.setObjectName("menuArchivo")
        self.menuCreditos = QtWidgets.QMenu(parent=self.menubar)
        self.menuCreditos.setObjectName("menuCreditos")
        main.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=main)
        self.statusbar.setObjectName("statusbar")
        main.setStatusBar(self.statusbar)
        self.actionDesarrolladores = QtGui.QAction(parent=main)
        self.actionDesarrolladores.setObjectName("actionDesarrolladores")
        self.btn_new_user = QtGui.QAction(parent=main)
        self.btn_new_user.setObjectName("btn_new_user")
        self.btnReportarTransferencias = QtGui.QAction(parent=main)
        self.btnReportarTransferencias.setObjectName("btnReportarTransferencias")
        self.btnHistorialTransferencias = QtGui.QAction(parent=main)
        self.btnHistorialTransferencias.setObjectName("btnHistorialTransferencias")
        self.btn_new_personal = QtGui.QAction(parent=main)
        self.btn_new_personal.setObjectName("btn_new_personal")
        self.btn_user = QtGui.QAction(parent=main)
        self.btn_user.setObjectName("btn_user")
        self.actionVer_Personal = QtGui.QAction(parent=main)
        self.actionVer_Personal.setObjectName("actionVer_Personal")
        self.btn_primera_quincena = QtGui.QAction(parent=main)
        self.btn_primera_quincena.setObjectName("btn_primera_quincena")
        self.btn_segunda_quincena = QtGui.QAction(parent=main)
        self.btn_segunda_quincena.setObjectName("btn_segunda_quincena")
        self.menuArchivo.addAction(self.btn_new_user)
        self.menuArchivo.addAction(self.btn_new_personal)
        self.menuArchivo.addAction(self.btn_user)
        self.menuArchivo.addAction(self.actionVer_Personal)
        self.menuArchivo.addAction(self.btn_primera_quincena)
        self.menuArchivo.addAction(self.btn_segunda_quincena)
        self.menuCreditos.addAction(self.actionDesarrolladores)
        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menubar.addAction(self.menuCreditos.menuAction())

        self.retranslateUi(main)
        QtCore.QMetaObject.connectSlotsByName(main)

    def retranslateUi(self, main):
        _translate = QtCore.QCoreApplication.translate
        main.setWindowTitle(_translate("main", "Gasolinera las Palmas"))
        self.menuArchivo.setTitle(_translate("main", "Acciones"))
        self.menuCreditos.setTitle(_translate("main", "Creditos"))
        self.actionDesarrolladores.setText(_translate("main", "Desarrolladores"))
        self.btn_new_user.setText(_translate("main", "Nuevo Usuario"))
        self.btn_new_user.setShortcut(_translate("main", "Ctrl+R"))
        self.btnReportarTransferencias.setText(_translate("main", "Reportar Transferencias"))
        self.btnHistorialTransferencias.setText(_translate("main", "Historial de Transferencias"))
        self.btn_new_personal.setText(_translate("main", "Nuevo Personal"))
        self.btn_user.setText(_translate("main", "Usuarios"))
        self.actionVer_Personal.setText(_translate("main", "Personal"))
        self.btn_primera_quincena.setText(_translate("main", "Primera Quincena"))
        self.btn_segunda_quincena.setText(_translate("main", "Segunda Quincena"))
