# Form implementation generated from reading ui file '/home/heracle/code/massmessages/view/userWindow.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1122, 480)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.table_users = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.table_users.setObjectName("table_users")
        self.table_users.setColumnCount(10)
        self.table_users.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_users.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_users.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_users.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_users.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_users.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_users.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_users.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_users.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_users.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_users.setHorizontalHeaderItem(9, item)
        self.verticalLayout.addWidget(self.table_users)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_refresh = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_refresh.setObjectName("btn_refresh")
        self.horizontalLayout.addWidget(self.btn_refresh)
        self.btn_delete = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_delete.setObjectName("btn_delete")
        self.horizontalLayout.addWidget(self.btn_delete)
        self.btn_edit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_edit.setObjectName("btn_edit")
        self.horizontalLayout.addWidget(self.btn_edit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Users Management"))
        item = self.table_users.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.table_users.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Primer Nombre"))
        item = self.table_users.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Segundo Nombre"))
        item = self.table_users.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Primer Apellido"))
        item = self.table_users.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Segundo Apellido"))
        item = self.table_users.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Usuario"))
        item = self.table_users.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "contraseña"))
        item = self.table_users.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Teléfono"))
        item = self.table_users.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Role"))
        item = self.table_users.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Creado"))
        self.btn_refresh.setText(_translate("MainWindow", "Refrescar"))
        self.btn_delete.setText(_translate("MainWindow", "Eliminar"))
        self.btn_edit.setText(_translate("MainWindow", "Editar"))
